[package]
name = "rgb-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
oklab = "1.0.1"
png = "0.17.11"
rayon = "1.8.1"
